### ISSUE TITLE
ポータブル版がない場合に対応

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [yamamoto-ryuzo/yr-qgis-portable-launcher2#14]
Traceback (most recent call last):
  File "ProjectFile.py", line 314, in <module>
    main()
  File "ProjectFile.py", line 225, in main
    os.chdir(qgis_install_dir)
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。: './QGIS3.38.1'

**Comment by yamamoto-ryuzo** [comment]
配布用プロファイルが必ず必要だったので、GITのもアップロードすることでエラー回避に変更
